# coding: utf-8

# category
# 大カテゴリ
Category.create(name: 'レディース', parent_id: 0, grandparent_id: 0)
Category.create(name: 'メンズ', parent_id: 0, grandparent_id: 0)
Category.create(name: 'ベビー・キッズ', parent_id: 0, grandparent_id: 0)
Category.create(name: 'インテリア・住まい・小物', parent_id: 0, grandparent_id: 0)
Category.create(name: '本・音楽・ゲーム', parent_id: 0, grandparent_id: 0)
Category.create(name: 'おもちゃ・ホビー・グッズ', parent_id: 0, grandparent_id: 0)
Category.create(name: 'コスメ・香水・美容', parent_id: 0, grandparent_id: 0)
Category.create(name: '家電・スマホ・カメラ', parent_id: 0, grandparent_id: 0)
Category.create(name: 'スポーツ・レジャー', parent_id: 0, grandparent_id: 0)
Category.create(name: 'ハンドメイド', parent_id: 0, grandparent_id: 0)
Category.create(name: 'チケット', parent_id: 0, grandparent_id: 0)
Category.create(name: '自動車・オートバイ', parent_id: 0, grandparent_id: 0)
Category.create(name: 'その他', parent_id: 0, grandparent_id: 0)
# 中カテゴリ
# レディース
Category.create(name: 'トップス', parent_id: 1, grandparent_id: 0)
Category.create(name: 'ジャケット/アウター', parent_id: 1, grandparent_id: 0)
Category.create(name: 'パンツ', parent_id: 1, grandparent_id: 0)
Category.create(name: 'スカート', parent_id: 1, grandparent_id: 0)
Category.create(name: 'ワンピース', parent_id: 1, grandparent_id: 0)
Category.create(name: '靴', parent_id: 1, grandparent_id: 0)
Category.create(name: 'ルームウェア/パジャマ', parent_id: 1, grandparent_id: 0)
Category.create(name: 'レッグウェア', parent_id: 1, grandparent_id: 0)
Category.create(name: '帽子', parent_id: 1, grandparent_id: 0)
Category.create(name: 'バッグ', parent_id: 1, grandparent_id: 0)
Category.create(name: 'アクセサリー', parent_id: 1, grandparent_id: 0)
Category.create(name: 'ヘアアクセサリー', parent_id: 1, grandparent_id: 0)
Category.create(name: '小物', parent_id: 1, grandparent_id: 0)
Category.create(name: '時計', parent_id: 1, grandparent_id: 0)
# 小カテゴリ
# レディース/トップス
Category.create(name: 'Tシャツ/カットソー(半袖/袖なし)', parent_id: 14, grandparent_id: 1)
Category.create(name: 'Tシャツ/カットソー(七分/長袖)', parent_id: 14, grandparent_id: 1)
Category.create(name: 'シャツ/ブラウス(半袖/袖なし)', parent_id: 14, grandparent_id: 1)
Category.create(name: 'シャツ/ブラウス(七分/長袖)', parent_id: 14, grandparent_id: 1)
Category.create(name: 'ポロシャツ', parent_id: 14, grandparent_id: 1)
Category.create(name: 'キャミソール', parent_id: 14, grandparent_id: 1)
Category.create(name: 'タンクトップ', parent_id: 14, grandparent_id: 1)
Category.create(name: 'ホルターネック', parent_id: 14, grandparent_id: 1)
Category.create(name: 'ニット/セーター', parent_id: 14, grandparent_id: 1)
Category.create(name: 'チュニック', parent_id: 14, grandparent_id: 1)
Category.create(name: 'カーディガン/ボレロ', parent_id: 14, grandparent_id: 1)
Category.create(name: 'アンサンブル', parent_id: 14, grandparent_id: 1)
Category.create(name: 'ベスト/ジレ', parent_id: 14, grandparent_id: 1)
Category.create(name: 'パーカー', parent_id: 14, grandparent_id: 1)

# size
Size.create(name: 'S')
Size.create(name: 'M')
Size.create(name: 'L')
Size.create(name: 'LL')

BrandGroup.create(name: 'レディース')
BrandGroup.create(name: 'メンズ')
BrandGroup.create(name: 'ベビー・キッズ')
BrandGroup.create(name: 'インテリア・住まい・雑貨')
BrandGroup.create(name: 'キッチン・食器')
BrandGroup.create(name: '時計')
BrandGroup.create(name: 'コスメ・香水・美容')
BrandGroup.create(name: 'テレビゲーム')
BrandGroup.create(name: 'スポーツ・レジャー')
BrandGroup.create(name: 'スマートフォン・携帯電話')
BrandGroup.create(name: 'バイク')
BrandGroup.create(name: '楽器')
BrandGroup.create(name: '自動車パーツ')
BrandGroup.create(name: '食品')
BrandGroup.create(name: '国内自動車本体')
BrandGroup.create(name: '外国自動車本体')

# brand
Brand.create(name: 'シャネル', brand_group_id: 1)
Brand.create(name: 'ナイキ', brand_group_id: 2)
Brand.create(name: 'ルイ・ヴィトン', brand_group_id: 1)
Brand.create(name: 'シュプリーム', brand_group_id: 2)
Brand.create(name: 'アディダス', brand_group_id: 2)

